import { Grid, LinearProgress, Stack, Typography } from "@mui/material";\nimport CheckCircleIcon from "@mui/icons-material/CheckCircle";\nimport PendingIcon from "@mui/icons-material/Pending";\nimport CancelIcon from "@mui/icons-material/Cancel";\nimport InsightsIcon from "@mui/icons-material/Insights";\n\nimport KpiCard from "./KpiCard";\nimport { useValidationStatistics } from "../hooks/useValidationStatistics";\nimport QuestionnaireProgressPanel from "./QuestionnaireProgressPanel";\nimport ValidationHeatmap from "./ValidationHeatmap";\nimport ValidationAnalyticsPanel from "./ValidationAnalyticsPanel";\nimport SeverityDistributionCard from "./SeverityDistributionCard";\nimport RejectedObservationsTable from "./RejectedObservationsTable";\n\ninterface Props {\n  dataCollectionId: string;\n}\n\nexport default function ValidationDashboard({\n  dataCollectionId,\n}: Props) {\n\n  const { data } =\n    useValidationStatistics(dataCollectionId);\n\n  if (!data) return null;\n\n  return (\n    <Stack spacing={2}>\n      <Grid container spacing={2}>\n        <Grid item xs={6} md={3}>\n          <KpiCard\n            title="Validated"\n            value={data.validated}\n            color="#16A34A"\n            icon={<CheckCircleIcon color="success"/>}\n          />\n        </Grid>\n\n        <Grid item xs={6} md={3}>\n          <KpiCard\n            title="Pending"\n            value={data.pending}\n            color="#D97706"\n            icon={<PendingIcon sx={{color:"#D97706"}}/>}\n          />\n        </Grid>\n\n        <Grid item xs={6} md={3}>\n          <KpiCard\n            title="Rejected"\n            value={data.rejected}\n            color="#DC2626"\n            icon={<CancelIcon color="error"/>}\n          />\n        </Grid>\n\n        <Grid item xs={6} md={3}>\n          <KpiCard\n            title="Completion"\n            value={`${data.completionRate}%`}\n            color="#2563EB"\n            icon={<InsightsIcon color="primary"/>}\n          />\n        </Grid>\n      </Grid>\n\n      <Stack spacing={0.5}>\n        <Typography variant="body2">\n          Overall completion\n        </Typography>\n\n        <LinearProgress\n          variant="determinate"\n          value={data.completionRate}\n          sx={{height:8,borderRadius:4}}\n        />\n\n        <Typography\n          variant="caption"\n          color="text.secondary"\n        >\n          {`${data.validated} validated • ${data.pending} pending • ${data.rejected} rejected`}\n        </Typography>\n      </Stack>\n\n      <RejectedObservationsTable
import SeverityDistributionPanel from "./SeverityDistributionPanel";
import ValidationHeatmapPanel from "./ValidationHeatmapPanel";
        dataCollectionId={dataCollectionId}
      />

      <ValidationHeatmapPanel
        dataCollectionId={dataCollectionId}
      />

      <QuestionnaireProgressPanel\n        dataCollectionId={dataCollectionId}\n      />\n\n      <SeverityDistributionCard\n        dataCollectionId={dataCollectionId}\n      />\n\n      <ValidationHeatmap\n        dataCollectionId={dataCollectionId}\n      />\n\n    \n      <ValidationAnalyticsPanel\n        dataCollectionId={dataCollectionId}\n      />\n\n    </Stack>\n  );\n}