package org.afdb.aikp.modules.quality.domain.enums;

public enum QualityDimension {
    COMPLETENESS,
    INTERNAL_CONSISTENCY,
    MATHEMATICAL_CONSISTENCY,
    RECONCILIATION,
    TEMPORAL_CONSISTENCY,
    CROSS_TEMPLATE_CONSISTENCY,
    SIGNIFICANT_FINDINGS,
    INSTITUTIONAL_REGULATORY_CONSISTENCY,
    MARKET_STRUCTURE_CONSISTENCY
}
