spring:

  datasource:

    url: jdbc:postgresql://localhost:5432/aikp

    username: aikp

    password: aikp

    driver-class-name: org.postgresql.Driver

  jpa:

    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:

      hibernate:

        format_sql: true

        jdbc:
          time_zone: UTC

  flyway:

    enabled: true

    default-schema: reference

    schemas:
      - reference

    create-schemas: true

    locations:
      - classpath:db/migration

    out-of-order: false

logging:

  level:

    org.hibernate.SQL: DEBUG

    org.springframework: INFO