spring:

  application:
    name: AIKP Platform

  profiles:
    default: dev

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

management:

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

springdoc:

  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui/index.html

logging:

  level:
    root: INFO

  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
