########################################
# APPLICATION
########################################

spring.application.name=aikp-backend

########################################
# DATASOURCE
########################################

spring.datasource.url=jdbc:postgresql://localhost:5432/aikp
spring.datasource.username=aikp
spring.datasource.password=aikp

spring.datasource.driver-class-name=org.postgresql.Driver

########################################
# JPA
########################################

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.default_schema=reference

########################################
# FLYWAY
########################################

spring.flyway.enabled=true
spring.flyway.default-schema=reference
spring.flyway.schemas=reference
spring.flyway.create-schemas=true
spring.flyway.out-of-order=true

# Flyway migrations are authoritative for database initialization
spring.flyway.baseline-on-migrate=false

########################################
# SERVER
########################################

server.port=8080